apiVersion: v1
kind: ConfigMap
metadata:
  name: schemas
  namespace: kafka
data:
  vehicle-gps-schema.json: |
    {
      "name": "vehicle_gps",
      "fields": [
        {"name": "vehicleId", "type": "string", "options": ["TRK-4521","TRK-4522","TRK-4523","TRK-4524","TRK-4525","TRK-4526","TRK-4527","TRK-4528","TRK-4529","TRK-4530"]},
        {"name": "lat", "type": "double", "min": 40.6, "max": 40.8},
        {"name": "lon", "type": "double", "min": -74.1, "max": -73.9},
        {"name": "status", "type": "string", "options": ["EN_ROUTE","IDLE","DELIVERING","RETURNING"]},
        {"name": "nextStop", "type": "string", "regex": "CUST-[0-9]{4}"},
        {"name": "estimatedArrival", "type": "long"}
      ]
    }

  engine-diagnostics-schema.json: |
    {
      "name": "engine_diagnostics",
      "fields": [
        {"name": "vehicleId", "type": "string", "options": ["TRK-4521","TRK-4522","TRK-4523","TRK-4524","TRK-4525","TRK-4526","TRK-4527","TRK-4528","TRK-4529","TRK-4530"]},
        {"name": "engineTemp", "type": "int", "min": 180, "max": 220},
        {"name": "fuelLevel", "type": "int", "min": 10, "max": 100},
        {"name": "alertLevel", "type": "string", "options": ["NORMAL","WARNING","CRITICAL"], "weights": [80,15,5]},
        {"name": "message", "type": "string", "options": ["All systems normal","Schedule maintenance soon","Check engine immediately","Low fuel warning"]}
      ]
    }

  fleet-telemetry-schema.json: |
    {
      "name": "fleet_telemetry",
      "fields": [
        {"name": "vehicleId", "type": "string", "options": ["TRK-4521","TRK-4522","TRK-4523","TRK-4524","TRK-4525","TRK-4526","TRK-4527","TRK-4528","TRK-4529","TRK-4530"]},
        {"name": "periodStart", "type": "long"},
        {"name": "avgSpeed", "type": "double", "min": 25.0, "max": 55.0},
        {"name": "idleTime", "type": "int", "min": 0, "max": 300},
        {"name": "distance", "type": "double", "min": 10.0, "max": 50.0},
        {"name": "fuelEfficiency", "type": "double", "min": 6.0, "max": 10.0}
      ]
    }

  driver-behavior-schema.json: |
    {
      "name": "driver_behavior",
      "fields": [
        {"name": "driverId", "type": "string", "options": ["DRV-781","DRV-782","DRV-783","DRV-784","DRV-785"]},
        {"name": "vehicleId", "type": "string", "options": ["TRK-4521","TRK-4522","TRK-4523","TRK-4524","TRK-4525","TRK-4526","TRK-4527","TRK-4528","TRK-4529","TRK-4530"]},
        {"name": "hardBrakes", "type": "int", "min": 0, "max": 5},
        {"name": "rapidAccel", "type": "int", "min": 0, "max": 3},
        {"name": "sharpTurns", "type": "int", "min": 0, "max": 4},
        {"name": "safetyScore", "type": "int", "min": 70, "max": 100}
      ]
    }

  delivery-updates-schema.json: |
    {
      "name": "delivery_updates",
      "fields": [
        {"name": "deliveryId", "type": "string", "regex": "DEL-[0-9]{4}"},
        {"name": "trackingNumber", "type": "string", "regex": "1Z999AA[0-9]{10}"},
        {"name": "status", "type": "string", "options": ["PICKED_UP","IN_TRANSIT","OUT_FOR_DELIVERY","DELIVERED","DELIVERY_ATTEMPTED"]},
        {"name": "estimatedDelivery", "type": "long"}
      ]
    }
