controller:
  ingressController:
    image:
      tag: "3.5"
    env:
      feature_gates: "FillIDs=true,GatewayAlpha=true"
    konnect:
      license:
        enabled: true
      enabled: true
      controlPlaneID: "c2ef4cf3-bda4-43f5-81a2-251c2ff056ef"
      tlsClientCertSecretName: konnect-client-tls
      apiHostname: "us.kic.api.konghq.com"

gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.11"
  env:
    konnect_mode: "on"
    vitals: "off"
    cluster_mtls: pki
    cluster_telemetry_endpoint: "c643a64bf5.us.tp.konghq.com:443"
    cluster_telemetry_server_name: "c643a64bf5.us.tp.konghq.com"
    cluster_cert: /etc/secrets/konnect-client-tls/tls.crt
    cluster_cert_key: /etc/secrets/konnect-client-tls/tls.key
    lua_ssl_trusted_certificate: system
    nginx_worker_processes: "1"
    upstream_keepalive_max_requests: "100000"
    nginx_http_keepalive_requests: "100000"
    proxy_access_log: "off"
    dns_stale_ttl: "3600"
  resources:
    requests:
      cpu: 1
      memory: "2Gi"
  secretVolumes:
    - konnect-client-tls
  manager:
    enabled: false
  proxy:
    stream:
      - containerPort: 9092
        servicePort: 9092
        protocol: TCP
        parameters:
          - "ssl"
